- Cargo.lock
- Cargo.toml
This PR updates cargo dependencies as well as moves wit-bindgen
dependencies to latest.
> Update cargo dependencies.

- Cargo.lock
- Cargo.toml
- example/Cargo.lock
- example/Cargo.toml
- src/commands.rs
- src/commands/build.rs
- src/commands/check.rs
- src/commands/new.rs
- src/lib.rs
This PR updates the dependencies of `cargo component` to the latest.
It includes the most recent changes to the component model and `wit-bindgen`.
> Update dependencies to latest.

- Cargo.lock
- Cargo.toml
- README.md
This PR updates the README so that the requirements and installation
sections come first.
Dependencies are also updated to the latest versions.
Closes #54.
> Update installation instructions in the README

- src/bindings.rs
- tests/build.rs
This PR fixes the up-to-date check when the target is a directory containing wit files.
We now parse the wit *before* the up-to-date check, which allows us to determine the additional wit dep paths to timestamp.
Fixes #65.
> Fix up-to-date check when target is a wit directory.

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/registry.rs
- tests/add.rs
- tests/new.rs
- tests/publish.rs
- tests/support/mod.rs
- tests/update.rs
Resolves [this issue](https://github.com/bytecodealliance/cargo-component/issues/77#issuecomment-1542600794)
> update to use RegistryStorage from warg

- Cargo.lock
- Cargo.toml
- README.md
- example/src/lib.rs
- src/bindings.rs
- src/commands/new.rs
- src/generator.rs
- tests/build.rs
- tests/publish.rs
- tests/update.rs
Another round of updates, notably changing the names of traits generated by `wit-bindgen` for users to implement to the name "Guest"
> Update to latest wit-bindgen/wasm-tools

- Cargo.lock
- Cargo.toml
- crates/wit/Cargo.toml
> Bump cargo-component to 0.3.0.

- .github/workflows/publish-binaries.yml
Publish binary for DEV releases and also for tagged releases
> chore: publish binaries

- .github/workflows/publish-binaries.yml
This PR attempts to minimize the size of published artifacts by enabling LTO, aborting on panic, and stripping debug information.
> Reduce the size of published artifacts.

- Cargo.lock
- Cargo.toml
- crates/wit/Cargo.toml
Pulling in the recently-published versions.
> Update wasm-tools dependencies

- README.md
- crates/wit/tests/add.rs
- crates/wit/tests/build.rs
- crates/wit/tests/publish.rs
- crates/wit/tests/update.rs
- src/commands/new.rs
- tests/build.rs
This PR adds semicolons to the WIT produced by `cargo component new` as well as to the tests.
> Add semicolons to WIT.

- README.md
> Update README Rust-analyzer setting

- Cargo.lock
- Cargo.toml
- crates/wit/Cargo.toml
> Bump version to 0.6.0.

- Cargo.lock
- Cargo.toml
- crates/wit/Cargo.toml
> Bump cargo-component to 0.7.0.

- .github/workflows/main.yml
> Update CI to setup wasmtime via release artifacts.

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- crates/wit/Cargo.toml
This PR also bumps `wit` to 0.7.0.
> Bump version to 0.8.0.

- src/bindings.rs
- tests/build.rs
> fix kebab case issue

- README.md
> Update install instruction to use --locked

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/wit/Cargo.toml
Forgot to delete these `Cargo.toml` lines. No longer used.
> removed unused warg-credentials dependency

- .github/workflows/main.yml
- src/lib.rs
- tests/run.rs
- tests/test.rs
> Update to -S cli instead of -S common for wasmtime commands

- Cargo.lock
- Cargo.toml
- src/lib.rs
Also, added `http` permission for `cargo component run`
> version bumped wasm-pkg-client

- Cargo.lock
- Cargo.toml
- src/bindings.rs
- src/generator.rs
- tests/build.rs
- tests/check.rs
- tests/clippy.rs
- tests/metadata.rs
> latest wasm-tools, and latest wit-bindgen
