README.md
This PR adds a `WASI Support` section to the README to explain why `cargo
component` targets `wasm32-unknown-unknown` by default.
Closes #25.
=> Add a `WASI Support` section to the README.

README.md, example/Cargo.toml, src/commands/add.rs, src/commands/new.rs, src/lib.rs, tests/add.rs
This PR updates the format for `Cargo.toml` to make it clearer as to what
gets imported and what gets exported.
It splits the former `dependencies` table into two tables `imports` and
`exports`.
Each dependency in those tables is uniformly specified as either:
```toml
dep = "path"
```
or:
```toml
dep = { path = "path" }
```
This removes the version numbers from the dependencies for now until such time
as they are useful.
A warning was added if we encounter the old `dependencies` table to warn users
they need to upgrade their `Cargo.toml` format; the tool doesn't attempt to do
so automatically (sorry).
Closes #28.
=> Update `Cargo.toml` format for `cargo component`. 

Cargo.lock, Cargo.toml
This PR bumps `cargo-component` dependencies to latest.
It includes updating `wit-bindgen` for the latest binding fixes.
=> Bump dependencies to latest.

Cargo.lock, Cargo.toml, src/commands/add.rs, src/commands/build.rs, src/commands/check.rs, src/commands/clippy.rs, src/commands/metadata.rs, src/commands/new.rs, tests/metadata.rs
Upstream cargo has [upgraded](https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L65) to clap v4.
`takes_value` has been deprecated.
`num_args` (the replacement for `takes_value`) will default `num_args` based on the `ArgAction` and doesn't need to be set for the verbose flag use-case. But there's one more change. Commands with ArgAction::Count must be u8.
Test caught this:
```bash
command=`"/Users/bhayes/repos/bytecodealliance/cargo-component/target/debug/cargo-component" "component" "add"`
code=101
stdout=""
stderr="thread \'main\' panicked at \'assertion failed: `(left == right)`\n  left: `u8`,\n right: `u32`: Argument `verbose`\'s selected action Count contradicts `value_parser` (ValueParser::other(u32))\', /Users/bhayes/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.1 …
```
=> chore: upgrade to clap v4

src/commands/add.rs, src/lib.rs, tests/build.rs, tests/check.rs, tests/clippy.rs, tests/metadata.rs
This PR implements support for handling workspaces and not individual
component packages.
`cargo-component` now scans the set of packages in the workspace for packages
with component metadata, generates bindings for only those packages, and then
also generates components only for those packages (for the build command).
Fixes https://github.com/bytecodealliance/cargo-component/issues/34.
=> Implement support for workspaces. 

Cargo.lock, Cargo.toml, README.md, example/Cargo.lock, example/Cargo.toml, example/src/lib.rs, src/commands/add.rs, src/commands/new.rs, src/lib.rs, tests/check.rs, tests/clippy.rs, tests/metadata.rs
This PR updates `cargo-component` to the latest dependencies.
In doing so, `wit-bindgen` has been updated to generate based on a "world" rather than bindings per import/export.
As such, this is a breaking change with user code as now there's a singular "bindings" crate that gets generated.
=> Update to latest dependencies.

README.md
This commit updates the installation instructions in the README to install from GitHub rather than the local repository.
=> Update installation instructions in README.

example/Cargo.lock, example/Cargo.toml, src/lib.rs
This PR turns on the `realloc` feature in `wit-bindgen-guest-rust` from the bindings now that it is behind a feature flag.
=> Fix realloc not present in bindings.

Cargo.lock, Cargo.toml, example/Cargo.lock, src/commands/add.rs
This PR updates `cargo-component`'s dependencies to the latest versions.
`toml_edit` is kept back at 0.14.x because that's still what cargo is using.
=> Update dependencies to latest.

Cargo.lock, Cargo.toml, README.md, example/Cargo.lock, example/backend.wit, example/cache.wit, src/commands/new.rs, src/lib.rs, tests/add.rs, tests/build.rs, tests/new.rs
This PR updates cargo-component's dependencies to latest.
It includes changes to `wit-component` to support the current binary format of the component model.
As a result of changes to wit-parser, interface definitions must now be wrapped in a declaring `interface <name>` scope.
=> Update cargo-component dependencies to latest.

docs/design/registries.md
[Rendered view](https://github.com/bytecodealliance/cargo-component/blob/f8bf935bd045b90de6c6482f144217f9b184e114/docs/design/registries.md)
This PR adds a design document for the developer experience surrounding using packages from a component registry in `cargo-component`.
Closes #42.
=> Add a design document around registry integration.

docs/design/registries.md
[Rendered version](https://github.com/bytecodealliance/cargo-component/blob/173afdaf83fc1d892215b495a4bd45b8b2fdd60f/docs/design/registries.md)
This PR updates the registry design doc to better describe target worlds.
It now fully separates WIT package dependencies used _only_ for parsing local WIT document targets and the component dependencies.
=> Update the registry design doc (again).

Cargo.lock, Cargo.toml, docs/design/registries.md, src/bindings.rs, src/metadata.rs, tests/registry.rs
This PR merges the `document` and `world` settings in Cargo.toml for specifying the target world to use from a package.
Additionally, it updates the resolution to first use `Resolve::select_world` to find the world to use.
As binary-encoded WIT packages don't currently encode a notion of a "default" world, the previous fallback is kept for parsing binary WIT packages.
Dependencies have also been updated.
Closes #51.
=> Merge the `document` and `world` settings.

Cargo.lock, Cargo.toml, build.rs, src/bin/cargo-component.rs, src/lib.rs, tests/build.rs
This PR adds a `produced-by` field for `cargo-component` in the producers section of the component created by `cargo component build`.
Closes #57.
=> Implement adding a producers section to output components.

Cargo.lock, Cargo.toml, src/bindings.rs, src/commands/add.rs, src/commands/new.rs, src/registry.rs, tests/add.rs, tests/new.rs, tests/registry.rs, tests/support/mod.rs, tests/update.rs
This PR implements a `--target` option that causes `cargo component new` to set the target to use in `Cargo.toml`.
It also generates `src/lib.rs` based on the exports of the target world, providing the necessary boilerplate code for users to immediately start implementing the component's exports.
A `--registry` option is also added to set the default registry of the project and is currently used to resolve the `--target` option until an internal default registry is implemented.
Additionally, a `--world` option was added to set the world to use when specifying a target WIT package.
=> Implement a `--target` option for `cargo component new`.

docs/design/registries.md
This PR fixes the examples in the registry integration design doc as the `document` field is no longer present.
=> Fix examples in registry integration design doc.

README.md, src/bin/cargo-component.rs, src/commands.rs, src/commands/doc.rs, src/commands/new.rs, src/lib.rs, tests/doc.rs
Add a `cargo component doc` subcommand, which generates API documentation for the user's component and optionally its dependencies.
=> Add a `doc` subcommand.

Cargo.lock, Cargo.toml, src/commands/clippy.rs, tests/check.rs, tests/clippy.rs
Comes on the heals of https://github.com/bytecodealliance/wit-bindgen/pull/563 and https://github.com/bytecodealliance/wasm-tools/pull/1002
=> Update wit-bindgen and wasm-tools dependencies

Cargo.lock, README.md, src/bin/cargo-component.rs, src/bindings.rs, src/commands.rs, src/commands/wit.rs, src/lib.rs, tests/publish.rs, tests/wit.rs
This PR implements a `wit publish` command that will publish the local target WIT package for a component to a warg registry.
It also implements support for generating bindings for interface exports on component dependencies.
=> Implement a `wit publish` command.

src/bindings.rs, src/commands/new.rs, src/registry.rs, tests/build.rs
This PR implements specifying WIT package target dependencies by `path`.
It allows for specifying local target dependencies that are themselves WIT packages, much like how `wit-parser` allows for deps to be found in a `deps` directory.
The `deps` behavior of `wit-parser` can be replicated by explicitly specifying the WIT's top level dependencies in with the following syntax:
```toml
[package.metadata.component.target]
path = "wit"
[package.metadata.component.target.dependencies]
"foo:bar" = { path = "wit/deps/foo-bar" }
"baz:jam" = { path = "wit/deps/baz-jam" }
...
```
=> Implement WIT package dependencies by `path`.

src/bindings.rs, src/registry.rs, tests/build.rs
This PR removes calls to `Resolve::push_dir` when processing target dependencies.
As a result, no WIT files will be parsed from a `deps` directory automatically, so each dependency must be specified in the target dependencies table.
This change performs roughly the same work that `push_dir` was doing, namely the topological sort of the dependencies so that they are parsed in the correct order.
It should now be possible to share a target dependency between other target dependencies, much like one would expect from the `deps` directory behavior from `Resolve::push_dir`.
=> Allow WIT package dependencies to be shared.

Cargo.lock, Cargo.toml, docs/design/registries.md, src/bindings.rs, src/commands/add.rs, src/commands/key.rs, src/commands/publish.rs, src/commands/wit.rs, src/lib.rs, src/metadata.rs, src/registry.rs, src/signing.rs, tests/publish.rs, tests/support/mod.rs
This PR updates `cargo-component` to the latest dependencies, including the latest `warg` crates.
It contains fixes for the following:
* Set the WIT package version when publishing with the `wit publish` command.
* Remove `metadata::Id` in favor of `warg_protocol::registry::PackageId`.
* Fix source generation for the `--target` option in the `new` command:
* Use snake case path components derived from package ids.
* Use correct path for referencing interface-owned types.
* Rename the `user` option to `key-name` for the `key` subcommands; this makes the command more consistent with the `warg` CLI tool.
* Use the `resolve_dependencies` function when publishing a WIT package with the `wit publish` command.
* Add a `processed-by` version to the producers section of the WIT package published …
=> Fixes with latest dependencies.

build.rs
The package fails to build when it is not in a git repository due to the usage of `env!("WASI_ADAPTER_VERSION")`, this fixes the issue
=> Export wasi adapter version even if git fails

src/bindings.rs, tests/build.rs
This fixes a mistake where the `Resolve` synthesized for an empty WIT package had a world but the world wasn't listed in the `Package` which caused an invalid custom section to be produced where no world was emitted. The world injected is registered with its parent package here to establish the relationship which avoids a bad custom section.
=> Fix structure of `Resolve` with an empty world

src/commands/new.rs
This PR updates the `cargo component new` command to use a git reference to the `cargo-component-bindings` crate until it is published to crates.io with the rest of `cargo-component`.
=> Use git dependency for bindings crate.

README.md, crates/wit/README.md
Installing `cargo-component` now gives this error:
```rust
cargo install --git https://github.com/bytecodealliance/cargo-component
Updating git repository `https://github.com/bytecodealliance/cargo-component`
error: multiple packages with binaries found: cargo-component, wit. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/bytecodealliance/cargo-component cargo-component`.
```
So we need to specify which "crate" to install.
Interestingly, I was getting the same error with the `wit` command that contained `--bin wit`, so I added the `wit` package there too. I am not sure what the `--bin wit` flag is doing.
I am on Windows 10, using Git Bash, if that's relevant.
=> Specify which binary to select in installation command

Cargo.lock, crates/core/Cargo.toml, crates/core/src/command.rs, crates/core/src/lib.rs, crates/core/src/terminal.rs, crates/wit/src/commands.rs, crates/wit/src/commands/add.rs, crates/wit/src/commands/build.rs, crates/wit/src/commands/init.rs, crates/wit/src/commands/key.rs, crates/wit/src/commands/publish.rs, crates/wit/src/commands/update.rs, src/bin/cargo-component.rs, src/commands/add.rs, src/commands/key.rs, src/commands/new.rs, src/commands/publish.rs, src/commands/update.rs, src/config.rs, src/lib.rs
This PR refactors the commands such that the built-in commands do not parse cargo options.
It will allow the built-in commands to fully define what options they support irrespective of what options cargo might support (e.g. `target`).
=> Refactor the commands to prevent cargo option parsing for built-ins.

src/commands/add.rs, tests/add.rs
Adds the `--target` flag to `cargo component add`, allowing the `package.metadata.component.target.dependencies` section to be manipulated by the `add` command.
=> Add the `--target` flag to `cargo component add`

crates/wit/src/lib.rs, crates/wit/tests/update.rs, src/lib.rs, tests/update.rs
This PR fixes both `cargo component update` and `wit update` to properly print out added/removed messages for dependencies that might have changed in `Cargo.toml`/`wit.toml`, rather than panic.
=> Fix update commands.

src/commands/add.rs, tests/add.rs
Add the `--path` flag to `cargo component add`, allowing dependencies to be resolved from local files. In this case, the version is defaulted to `*`.
=> Add `--path` to `cargo component add`

crates/core/src/registry.rs, crates/wit/src/commands/add.rs, crates/wit/src/config.rs, crates/wit/tests/add.rs, tests/add.rs
This PR adds a `--path` option to the `wit add` command, similar to how PR #113 added the option to `cargo component add`.
It also fixes the formatting such that dependencies that need an inline table are written with an inline table.
=> Add `--path` option to `wit add` command.

Cargo.lock, Cargo.toml, crates/bindings/src/lib.rs, crates/macro/src/lib.rs, example/Cargo.lock, tests/build.rs
This PR updates dependencies and `wit-bindgen` to a commit that has a fix for specifying the path to the `bitflags` crate re-export, allowing `cargo-component` targets to contain `flags` types.
Updated an existing test to cover the use of the `flags` type.
Fixes #119.
=> Fix code generation for `flags`.

src/generator.rs, tests/new.rs
This PR implements the missing support in generating code for the `--target` option of `cargo component new` when the targeted world exports items with owned and borrowed resources.
=> Implement generating target code for resources.

src/commands/new.rs
This sets up dir-local variables that configure lsp-mode appropriately for a `cargo component` project.
=> Add emacs editor config option for `cargo component new`

src/bindings.rs, tests/build.rs
This PR fixes the merging of a world made up of the exports of a component dependency such that it also imports any owning interfaces for types imported by the dependency.
=> Fix missing interface imports for component dependencies.

crates/wit/src/lib.rs, src/bindings.rs, src/lib.rs
This PR changes `cargo-component` so that it no longer implicitly sets the version numbers on any local WIT definitions.
Closes #129.
Closes #111.
=> Remove implicit versioning in WIT resolves.

Cargo.toml, crates/wit/src/lib.rs, src/bindings.rs
Previously, the toposort performed for WIT dependencies would skip visiting any of the dependencies of decoded binary packages because it was assumed that it was unnecessary due to the fact the dependency information was encoded in the package.
However, wit-parser doesn't merge interfaces unless they have identical definitions (see https://github.com/bytecodealliance/wasm-tools/issues/1191).
This means that we run into problems when a decoded binary package is merged *before* a dependency that contains the full (or otherwise disjoint) definition of the interface.
To work around this issue, users should be able to add an explicit dependency on any transitive dependencies so that they get merged first.
For that to work, we need to visit any dependencies on decoded binary packages as well, …
=> Fix toposort for decoded binary WIT packages.

crates/wit/src/commands/add.rs, crates/wit/src/config.rs, crates/wit/src/lib.rs, crates/wit/tests/publish.rs, crates/wit/tests/support/mod.rs, crates/wit/tests/update.rs, src/commands/publish.rs, src/lib.rs, tests/publish.rs
This PR adds registry metadata to components published to a registry with
`cargo component publish` and `wit publish`.
=> Add registry metadata to published components.

docs/design/registries.md, example/Cargo.lock, example/Cargo.toml, src/bindings.rs, src/commands/add.rs, src/commands/new.rs, src/lib.rs, src/metadata.rs, src/registry.rs, tests/build.rs
This PR makes `target.path` in the metadata default to a `wit` directory, if present.
This makes the `wit` directory a canonical directory, much like `src` is for source code.
Users may still override the path to find their local target definition.
Closes #134.
=> Use a default target path of `wit`.

src/lib.rs, src/metadata.rs, tests/build.rs
This PR adds a `package.metadata.component.adapter` field to `Cargo.toml` which is the path to the WASI module adapter to use.
If present, the specified file is used to adapt WASI preview1 to preview2.
If not present, the built-in WASI module adapter is used instead.
The intention with this change is to allow users control over how WASI is adapted in cases where the built-in adapter is not the desired one to use.
=> Add an `adapter` setting to `Cargo.toml`.

src/lib.rs, src/metadata.rs, tests/build.rs
This PR fixes a bug where the `adapter` setting in `Cargo.toml` wasn't being treated as relative to the manifest directory.
This PR also improves the diagnostics relating to a mismatched preview1 adapter by changing the order in which we call `module` and `adapter` on `ComponentEncoder`.
=> Make the adapter path in `Cargo.toml` relative to the manifest dir.

README.md, src/lib.rs, tests/build.rs
This fixes two things:
1. The error message when the `adapter` config setting point at something that is not a WebAssembly module.
2. The README section about WASI support; it now includes information about how to build the adapter module from source and use the `adapter` config setting.
=> Improve WASI adapter support.

.github/workflows/publish-to-crates-io.yml, Cargo.lock, Cargo.toml, README.md, ci/publish.rs, crates/wit/Cargo.toml, crates/wit/README.md, src/commands/new.rs
This PR adds a GitHub action (based on a similar one from Wasmtime) for publishing the crates when new tags are created.
This also bumps the crate versions to 0.2.0, which will be the first versions of the crates published.
=> Add GitHub actions for publishing crates.

Cargo.lock, Cargo.toml, crates/macro/Cargo.toml, crates/macro/src/lib.rs, src/generator.rs, tests/build.rs
This adds custom derive attributes to the generate macro. It also fixes a bug where package version was not appended to the hash map of exports
Closes #148
=> feat(macro): Adds custom derive attributes

crates/macro/src/lib.rs, tests/build.rs
This PR fixes bindings generation for the exports of interfaces coming from versioned packages (i.e. the WIT package directive has a version on it).
The issue is that the export map passed through to wit-bindgen is expecting _not_ to have the version on the interface name as the version is associated with the package and not the interface.
The fix is to stop appending the version number when populating the exports map.
=> Fix bindings generation for exports of versioned interfaces.

Cargo.lock, Cargo.toml, crates/bindings/Cargo.toml, crates/macro/Cargo.toml, crates/macro/src/lib.rs, src/bin/cargo-component.rs, src/bindings.rs, src/commands/add.rs, src/commands/new.rs, src/commands/publish.rs, src/commands/update.rs, src/lib.rs, src/metadata.rs, tests/build.rs, tests/support/mod.rs
This PR alters how bindings generation works in `cargo-component`.
Previously, `cargo-component` would encode a target world for the `generate!` macro to decode. The macro would decode the target and feed it to `wit-bindgen` and expand to the generated bindings.
This approach had a few drawbacks:
* compilation times for projects increased as `wit-bindgen` had to be built from the component itself.
* rust-analyzer would not re-expand the `generate!` macro on WIT file changes as it does not add a source dependency via `include_bytes!`.
* "go to definition" doesn't work with rust-analyzer as the bindings code was entirely from the macro expansion.
To fix all three issues, `cargo-component` now generates the bindings source file itself and the macro simply expands to `include!` it.
This cuts …
=> Refactor bindings generation.

Cargo.lock, Cargo.toml, crates/wit/Cargo.toml
This also bumps `wit` to 0.3.0.
=> Bump cargo-component version to 0.4.0.

README.md
Add information about `cargo-binstall` now that we're publishing release artifacts.
=> Update README installation instructions.

.github/workflows/publish-binaries.yml
Until someone needs a linux aarch64 prebuilt artifact and wants to get a proper cross-compilation for it (or upstream changes to warg to remove the dep on openssl), this PR removes it from the publish matrix.
=> Remove linux aarch64 published artifact for now.

src/bin/cargo-component.rs, src/commands.rs, src/commands/add.rs, src/commands/publish.rs, src/commands/update.rs, src/commands/upgrade.rs, src/lib.rs, tests/support/mod.rs, tests/upgrade.rs
Installs the latest version of cargo-component and upgrade to the corresponding version of cargo-component-bindings.
Follow-up to https://github.com/bytecodealliance/cargo-component/pull/167#issuecomment-1783593614.
Before merge this needs at least:
In particular I would like to draw the reviewer's attention to:
- Design decision to unconditionally `cargo-install` and then ~~`exec`~~ delegate to either the existing binary or newly installed binary (unknown to us) for the rest of the job, as originally mentioned here: https://github.com/bytecodealliance/cargo-component/pull/167#issuecomment-1783943366.
- `cargo-install` part is currently completely untested. (Though it Works For Me™.) For now I've gated it behind `#[cfg(test)]` so I can still at least have the tests delegate to a child …
=> Add `upgrade` subcommand

crates/core/src/registry.rs
Currently, when a component dependency is specified as a string it is assumed to be the version of the dependency on the registry. If, however, the user thinks that this could be path to a local wit definition, the error message is very confusing.
This changes adds a bit more context so hopefully the issue is clearer.
=> Better error message when deserializing `RegistryPackage`

crates/macro/src/lib.rs
This PR suppresses dead code warnings caused by unused imports in the generated bindings.
=> Suppress dead code warnings in bindings.

.github/workflows/main.yml
This PR is cherry-picked from the `release-0.4.0` branch to ensure that CI runs for PRs and merges on release branches.
=> Ensure CI runs on release branches.

Cargo.lock, Cargo.toml, crates/bindings/Cargo.toml, crates/wit/Cargo.toml, example/Cargo.lock, example/wit/example.wit, tests/new.rs, tests/publish.rs, tests/update.rs
This PR updates crate dependencies to latest.
To keep compatibility with Wasmtime 14 (until the next release), the adapters have not been updated.
Also fixes a few tests containing WIT that were missed when adding semicolons, as they are now required by default with this update.
=> Update crate dependencies.

src/commands/upgrade.rs, src/lib.rs, tests/build.rs, tests/upgrade.rs
This PR fixes the warning emitted when a mismatched bindings version crate is detected such that it no longer warns when the bindings crate version is compatible, but not the same version (i.e. `0.4.1` when cargo-component is `0.4.0`).
Likewise, the `upgrade` command no longer attempts to downgrade the version of the bindings crate when it would otherwise be compatible.
The upgrade tests no longer attempt the install, which require a long time to just verify that a `cargo install cargo-component` would succeed, which isn't terribly useful.
The warning and upgrade command now both detect when cargo-component is outdated and instruct the user appropriately.
=> Fix bindings version warning and upgrade command.

src/commands/new.rs
Add `--workspace` and `--all-targets` switches to both vscode and emacs configs, that are generated in `cargo component new`. This is in line with what rust-analyzer uses when
`rust-analyzer.check.overrideCommand` is empty.
Fixes #203 .
=> Check workspace with all targets in vscode, emacs configs

src/commands/add.rs, src/commands/publish.rs, src/config.rs, tests/add.rs, tests/support/mod.rs
Try to use current package in the `add` and `publish` command, when `-p` is not supplied and we are in a workspace.
Also isolate each test run. Previously all tests were sharing the same target/tests/Cargo.toml, which each test was modifying. This made order in which tests run significant and difficult to debug. Add test `two_projects_in_one_workspace_validate_add_from_path` which cretes two projects in the same workspace to make sure we modify the current package's manifest.
=> Use current package with `add`, `publish` when in a workspace

README.md, src/commands/new.rs, tests/build.rs, tests/check.rs, tests/clippy.rs, tests/metadata.rs, tests/new.rs, tests/support/mod.rs
This PR renames the `--reactor` option for the `new` subcommand to `--lib`.
It maintains an alias of `--reactor` for backwards compatibility.
Updated the tests to use `--lib` and added a test to ensure `--reactor` is still respected.
Closes #198.
=> Rename `--reactor` to `--lib` for `new` subcommand.

src/commands/new.rs, tests/build.rs, tests/check.rs, tests/clippy.rs, tests/metadata.rs
Fixes #204
`cargo component add` now spawns `cargo add cargo-component-bindings` . This has a few implications:
* It makes the command a bit slower as it needs to fetch the metadata from the network
* It uses the latest version by default.
* When in a workspace, and `cargo-component-bindings` is already defined as a workspace dependency, it uses the workspace version.
`cargo component upgrade` was not changed. I believe this command does too much and should be reconsidered.
Tests did not have to be changed, but checking a specific `cargo-component-bindings` version in tests might be problematic.
=> Spawn `cargo add` in the `new` command

.github/workflows/main.yml
This prevents being rate limited on the release downloads.
=> Add missing GH token for installing Wasmtime.

src/lib.rs
Remove the TODO comment and use `workspace_default_packages` now that it is implemented since Rust 1.71.
=> Use `workspace_default_packages` now that it is implemented.

src/bindings.rs, src/metadata.rs
Add support for the `std_feature` flag in
`[package.metadata.component.bindings]`, so that cargo-component can produce no_std components.
=> Add support for `std_feature`

Cargo.lock, Cargo.toml, src/bindings.rs, src/commands/add.rs, src/commands/publish.rs, src/config.rs, src/lib.rs, src/metadata.rs, src/registry.rs
This PR includes the following improvements to `cargo-component`:
* `cargo-component` now componentizes based off the presence of component type information custom sections rather than always requiring a `[package.metadata.component]` section be present in `Cargo.toml`.
* Bindings generation will now occur if a `wit` directory is present and `[package.metadata.component]` is not present in `Cargo.toml`.
* Fix a panic in `cargo component add` if it encounters expected items that are not tables in `Cargo.toml`.
* Fix not setting implicit tables for intermediate tables for the `cargo component add` command.
* Fix not displaying anything when `--help` is present for commands passed directly to `cargo`.
* `cargo-component` now uses the command adapter for `bin` examples and test/bench …
=> Various improvements to `cargo-component`.

README.md
Given where Wasmtime and WASI 0.2.0 are, I think it's probably time to remove this blurb from the README.
=> Remove status section from the README.

Cargo.lock, Cargo.toml, crates/wit/Cargo.toml
This also bumps `wit` to 0.8.0.
=> Bump `cargo-component` version to 0.9.0.

src/bindings.rs, src/lib.rs, tests/build.rs
This PR fixes a panic originating in `wit-bindgen` that occurs when a component dependency exports an interface that contains a used type.
Previously, the bindings generation only added used interfaces for types directly used by the component's world (i.e. from exported functions).
The fix was to do the same for any exported interfaces as well.
Also added some more `log::debug!` for context around bindings generation.
Fixed an incorrect reason being logged for when the bindings source file doesn't exist.
Fixes #252.
=> Fix panic in bindings generation for component dependencies.

src/generator.rs, tests/new.rs
This PR fixes the code generated by the `--target` option of the `new` subcommand when the exports contains a resource.
The code now conforms to the latest `wit-bindgen` output.
=> Fix `new --target` option for exports with resources.

src/lib.rs, tests/build.rs
This PR prevents bindings from being generated for "normal" cargo project.
Bindings will be generated if the project contains a `[package.metadata.component]` section in `Cargo.toml` or if it contains a `wit` subdirectory.
Fixes #258.
=> Prevent bindings generation for normal cargo projects.

crates/core/src/command.rs
This pull request add a message displayed after the help message, which notifies the unrecognized subcommands are passed to cargo. 
Refer to #138  for details
=> Help mesasage improvement (#138)

tests/build.rs, tests/check.rs, tests/doc.rs, tests/new.rs, tests/update.rs
This one was fun to track down. CI tests were failing but couldn't reproduce locally. Different Rust versions.
The test assertions check against the Rust `stderr` output and those messages changed.
For example, `Finished release [optimized] target(s)` is now ```Finished `release` profile [optimized] target(s)```.
=> fix test assertions after rust upgrade

src/commands/new.rs
This adds a default `[profile.release]`:
```toml
[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
```
The `cargo component build --release` of the `cargo component new --lib` output goes from `1.6 MB` -> `52 KB`.
=> Add `profile.release` to `Cargo.toml` generated by `cargo component new`

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/registry.rs, crates/wit/src/commands/key.rs, crates/wit/src/commands/publish.rs, crates/wit/src/lib.rs, crates/wit/tests/support/mod.rs, src/commands/key.rs, src/commands/publish.rs, src/lib.rs, tests/publish.rs, tests/support/mod.rs
This is a small update to update to the latest [Warg release](https://github.com/bytecodealliance/registry/releases/tag/v0.4.2). Supports federation across registries.
=> Update to latest Warg release to support registry federation

README.md
Documents additional dependencies. Ran into this while setting up a new Ubuntu-based environment from scratch on stream today. Thanks!
=> Document additional `cargo-component` requirements

src/lib.rs, tests/build.rs
This patch reads the project's Cargo configuration and uses the build target specified in it. This ensures that `cargo component build` will respect the target configuration in the `.cargo/config.toml` file and the value of the `CARGO_BUILD_TARGET` environment variable.
close https://github.com/bytecodealliance/cargo-component/issues/106
close https://github.com/bytecodealliance/cargo-component/issues/290
cc @calvinrp
=> Respect build target from cargo config

src/bindings.rs, src/commands/new.rs, src/lib.rs, tests/run.rs
Such as the case described in #314.
cc @calvinrp 
close #314
=> Stop generating the bindings file for projects without wit files and dependencies

Cargo.lock, Cargo.toml, crates/core/src/registry.rs, crates/wit/src/commands/add.rs, crates/wit/src/lib.rs, src/bin/cargo-component.rs, src/commands/add.rs, src/commands/new.rs, src/commands/publish.rs, src/commands/update.rs, src/config.rs, src/registry.rs
This adds back in support for offline deps. It required a change to the dependency resolver to error early if offline was requested without a lock file present
=> feat(*)!: Adds back support for the offline flag

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/registry.rs, crates/wit/Cargo.toml, crates/wit/README.md, crates/wit/src/commands/publish.rs, crates/wit/src/lib.rs, crates/wit/tests/add.rs, crates/wit/tests/publish.rs, crates/wit/tests/support/mod.rs, crates/wit/tests/update.rs, src/bindings.rs, src/commands/publish.rs, src/config.rs, src/lib.rs, tests/add.rs, tests/new.rs, tests/publish.rs, tests/support/mod.rs, tests/update.rs
This finishes replacing a direct dependency on warg with the newly released published functionality in wasm-pkg-tools. Please note that this removes some warg specific flags and it updates tests.
=> ref(*)!: Updates all code to use the new publish functionality in wkg

src/lib.rs
Compare the contents of `bindings.rs` before overwriting. If no changes are detected, skip the overwrite to prevent unnecessary recompilation.
=> Avoid overwriting `bindings.rs` if content is unchanged

src/bindings.rs
Use the default `bitflags_path`, because it's now the same as what we were overriding it to be. And add a comment to the `runtime_path` option, to explain why we override it.
=> Simply the options used with wit-bindgen-rust.

Cargo.lock
atty is no longer maintained, so update to ptree 0.5.1 which removes the atty dependency.
=> Update to ptree 0.5.1, to remove the atty dependency.

README.md
Rust has a new wasm32-wasip2 target, which may be easier to use in some situations, but it doesn't currently support all of `cargo component`'s features. Add a README.md section explaining the differences between the two.
=> Docuent cargo component's' relationship with the new wasip2 target.

README.md
Update the documentation talking about Rust's wasm32-wasip2 feature. We do hope to make use of it in `cargo component`, though it's not a trivial change.
This is inspired by #355.
=> Update the README to discuss the wasm32-wasip2 feature.

src/commands/new.rs
This commit effectively reverts #289 and removes the generated `[profile.release]` section from `Cargo.toml` when executing `cargo component new`. The PR mentions that a default release build decreases from 1.6M to 52KB and that was likely due to stripping DWARF debugging information rather than many of the other settings configured. Nowadays for example a default release build (with no extra configuration and no `profile.release`) is around 50KB because rustc/cargo have started stripping debuginfo by default in release mode. That means that the original motivation is still solved, the "default" build is not an alarmingly large 1.6M.
Otherwise the various settings configured here can have negative effects which aren't always easy to debug if you're not familiar with them, for example:
* …
=> Remove generated `[profile.release]` from new projects

src/config.rs
To allow using `cargo-component` as a library.
=> make `CargoArguments::parse_from` public

Cargo.lock, src/lib.rs, tests/build.rs
Depends on #371. Adds support for component-native annotations. I wasn't quite sure what to put in the "language field" for the top-level component, but I figured "Rust" would be a good fit. Thanks!
```text
$ wasm-tools metadata show component.wasm
╭──────────────┬─────────────────────────╮
│ KIND         ┆ VALUE                   │
╞══════════════╪═════════════════════════╡
│ kind         ┆ component               │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ name         ┆ <unknown>               │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ range        ┆ 0x0..0x2c9f9b           │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ processed-by ┆ wit-component [0.216.0] │
╰──────────────┴─────────────────────────╯
```
```text
$ wasm-tools metadata show component.wasm …
```
=> Annotations

Cargo.toml
just a patch release: only change from 0.21.0 is https://github.com/bytecodealliance/cargo-component/pull/381 which pins a dep to not use semver
=> set version to 0.21.1

Cargo.lock, Cargo.toml, src/git.rs, src/lib.rs
Gets the commit hash from the component package's Git repository, if available, and writes it to the revision field of the component metadata. Resolves issue #378
=> Add Git commit hash to the revision field of component metadata

Cargo.lock, Cargo.toml
https://github.com/bytecodealliance/cargo-component/pull/383 broke the binary build https://github.com/bytecodealliance/cargo-component/actions/runs/14040229083, which is not checked prior to merge. The root cause is depending on OpenSSL in a cross-compiling context, which was not trivial to resolve. But there is also no reason to actually depend on OpenSSL, since our use of `git2` isn't related to connecting to servers. So, this PR disables all of the features of git2, because they are not needed.
=> git2 dep: set default-features = false

.github/workflows/main.yml
CI is broken currently, apparently because sccache-action@v0.0.4 is using an azure service that was taken offline on April 15:
https://github.com/bytecodealliance/cargo-component/actions/runs/14503281869/job/40687667218#step:7:15
=> CI workflow: upgrade sccache-action to latest version

src/generator.rs, tests/new.rs
Single-element tuples in Rust require a trailing comma to distinguish them from parentheses used for grouping. The generator was producing (String) instead of (String,) for single-element tuples, causing compilation errors.
This fix adds logic to append a comma when generating single-element tuples in the TypeDefKind::Tuple case.
I have added a conditional after the tuple loop and a test for the expected behavior, let me know if there is anything else I should do!
=> Fix single-element tuple generation in WIT bindings
